import Link from 'next/link';
import {
  ArrowRight, BarChart3, Calculator, Check, ChevronRight,
  Coins, FileSearch, Gem, LineChart, PieChart, Rocket, Search, ShieldCheck, Sparkles,
  TrendingUp, WalletCards,
} from 'lucide-react';
import type { MarketPulseData } from './MarketPulse';
import CompanyLogo from '@/features/stocks/components/CompanyLogo';
import GlobalMarketSearch from './GlobalMarketSearch';

interface Props {
  data: MarketPulseData;
}

const card = 'rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900';

export default function HomeLanding({ data }: Props) {
  const { featuredStock, gold, topIpo, zakatNisab } = data;
  const positiveStock = featuredStock.changePct >= 0;

  return <main className="overflow-hidden bg-white text-slate-900 dark:bg-slate-950 dark:text-slate-100">
    <section className="relative border-b border-slate-200 bg-gradient-to-br from-sky-50 via-white to-emerald-50/70 py-7 dark:border-slate-800 dark:from-slate-950 dark:via-slate-950 dark:to-emerald-950/20 lg:py-9">
      <div className="pointer-events-none absolute inset-0 opacity-40 [background-image:linear-gradient(to_right,#dbeafe_1px,transparent_1px),linear-gradient(to_bottom,#dbeafe_1px,transparent_1px)] [background-size:44px_44px] [mask-image:linear-gradient(to_bottom,black,transparent_90%)] dark:opacity-10" />
      <div className="container relative mx-auto grid items-center gap-7 lg:grid-cols-[1.05fr_0.95fr]">
        <div className="max-w-2xl">
          <span className="inline-flex rounded-full border border-sky-200 bg-sky-100/70 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.16em] text-sky-700 dark:border-sky-800 dark:bg-sky-950 dark:text-sky-300">Ethical intelligence for modern markets</span>
          <h1 className="mt-4 text-4xl font-black leading-[1.04] tracking-tight text-slate-950 dark:text-white sm:text-5xl">Research markets with clarity. <span className="text-sky-600">Invest with confidence.</span></h1>
          <p className="mt-4 max-w-xl text-sm leading-6 text-slate-600 dark:text-slate-300">Stocks, IPOs, precious metals and Shariah screening—intelligent tools in one trusted platform.</p>
          <GlobalMarketSearch />
          <div className="mt-5 flex flex-wrap gap-3"><Link href="/stocks" className="inline-flex items-center gap-2 rounded-lg bg-sky-600 px-5 py-2.5 text-xs font-bold text-white shadow-lg shadow-sky-600/20 hover:bg-sky-700">Explore Markets <ArrowRight className="h-3.5 w-3.5" /></Link><Link href="/about" className="inline-flex items-center gap-2 rounded-lg border border-emerald-300 bg-white px-5 py-2.5 text-xs font-bold text-emerald-700 hover:bg-emerald-50 dark:border-emerald-800 dark:bg-slate-900 dark:text-emerald-300">Check Shariah Compliance <ShieldCheck className="h-4 w-4" /></Link></div>
          <div className="mt-5 grid max-w-xl gap-2 sm:grid-cols-3"><TrustMini icon={<ShieldCheck />} title="AAOIFI Standard No. 21" /><TrustMini icon={<BarChart3 />} title="Live market intelligence" /><TrustMini icon={<Sparkles />} title="Stocks · IPOs · Metals" /></div>
        </div>

        <div className="relative mx-auto min-h-[310px] w-full max-w-xl">
          <div className={`${card} absolute left-0 top-8 w-[68%] p-4`}><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><CompanyLogo src={featuredStock.logoUrl} symbol={featuredStock.symbol} name={featuredStock.name} size="lg" /><div className="min-w-0"><span className="text-[8px] font-bold uppercase tracking-wider text-slate-400">Featured stock</span><h3 className="truncate text-sm font-black">{featuredStock.name}</h3><span className="text-[9px] text-slate-500">{featuredStock.symbol} · India</span></div></div><span className="shrink-0 rounded-md bg-emerald-100 px-2 py-1 text-[8px] font-bold text-emerald-700">Shariah Compliant</span></div><div className="mt-3 flex items-end justify-between"><div><strong className="text-xl">{featuredStock.price}</strong><p className={`text-[10px] font-bold ${positiveStock ? 'text-emerald-600' : 'text-rose-600'}`}>{featuredStock.change}</p></div><MiniChart color="#0ea5e9" /></div></div>
          <div className={`${card} absolute right-0 top-0 w-[42%] p-4`}><div className="flex items-center gap-2 text-xs font-bold"><span className="rounded-lg bg-amber-100 p-2 text-amber-600"><Coins className="h-4 w-4" /></span>Gold 24K</div><strong className="mt-4 block text-lg">{gold.price10g}</strong><span className={`text-[10px] font-bold ${gold.isPositive ? 'text-emerald-600' : 'text-rose-600'}`}>{gold.changeDisplay}</span></div>
          <div className={`${card} absolute bottom-0 right-3 w-[48%] p-3.5`}><div className="flex items-center gap-2 text-[11px] font-bold"><span className="rounded-lg bg-rose-100 p-2 text-rose-600"><Rocket className="h-4 w-4" /></span>Live IPO GMP</div><h3 className="mt-2 truncate text-xs font-black">{topIpo.name}</h3><div className="mt-1 flex items-end justify-between"><strong className="text-base text-rose-600">{topIpo.gmpPercentage != null ? `+${topIpo.gmpPercentage}%` : topIpo.gmpDisplay}</strong><span className="rounded bg-emerald-100 px-2 py-1 text-[8px] font-bold text-emerald-700">{topIpo.status}</span></div></div>
          <div className={`${card} absolute bottom-7 left-5 w-[34%] p-3.5`}><div className="flex items-center gap-2 text-[11px] font-bold"><Calculator className="h-4 w-4 text-emerald-600" />Zakat Nisab</div><strong className="mt-2 block text-sm">{zakatNisab.silverNisabValue}</strong><span className="text-[8px] text-slate-500">Silver benchmark</span></div>
        </div>
      </div>
    </section>

    <section className="border-b border-slate-200 bg-white py-4 dark:border-slate-800 dark:bg-slate-950"><div className="container mx-auto grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><CategoryLink href="/stocks" icon={<TrendingUp />} title="Stock Intelligence" note="Research. Analyse. Invest." tone="sky" /><CategoryLink href="/ipo" icon={<Rocket />} title="IPO Tracker" note="GMP, dates and allotment." tone="rose" /><CategoryLink href="/gold" icon={<Coins />} title="Precious Metals" note="Gold, silver and platinum." tone="amber" /><CategoryLink href="/zakat" icon={<Calculator />} title="Zakat & Purification" note="Calculate and invest ethically." tone="emerald" /></div></section>

    <section className="bg-slate-50/70 py-14 dark:bg-slate-900/30"><div className="container mx-auto"><SectionHeading eyebrow="Products" title="Everything you need to research with confidence." copy="Powerful tools for smarter, ethical investing across Indian and global markets." /><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><ProductCard href="/stocks" icon={<TrendingUp />} title="Stocks" copy="Fundamental, technical and Shariah-compliant stock research." items={['Detailed company analysis','Technical indicators','Shariah compliance screening']} preview={`${featuredStock.symbol}  ${featuredStock.price}`} tone="sky" /><ProductCard href="/ipo" icon={<Rocket />} title="IPOs" copy="Track upcoming and live IPOs with GMP and subscription insights." items={['Live GMP and subscription','Key dates and analysis','Compare with listed peers']} preview={`${topIpo.name}  ${topIpo.gmpDisplay}`} tone="rose" /><ProductCard href="/gold" icon={<Gem />} title="Precious Metals" copy="Track gold, silver and platinum with historical prices." items={['Live and historical prices','Interactive trend charts','Price alerts and calculators']} preview={`Gold 24K  ${gold.price10g}`} tone="amber" /><ProductCard href="/zakat" icon={<WalletCards />} title="Islamic Wealth" copy="Track Zakat, purification and ethical investing." items={['Zakat calculator','Income purification','Screening guidance']} preview={`Nisab  ${zakatNisab.silverNisabValue}`} tone="emerald" /></div></div></section>

    <section className="py-14"><div className="container mx-auto"><SectionHeading title="Powerful tools, simple experience." copy="Designed to make complex research clear, visual and meaningful." /><div className="mt-9 space-y-10"><Showcase title="Shariah-compliant stock research" copy="Get a complete view of any company with price charts, key ratios, growth trends and Shariah compliance status—all in one place." bullets={['Price charts with key indicators','Valuation and financial highlights','AAOIFI-based compliance checks']} href="/stocks" cta="Try the Stock Screener" preview="stock" /><Showcase title="Track IPOs and precious metals with ease" copy="Stay updated on IPO GMP and subscription demand while tracking gold, silver and platinum prices with useful calculators." bullets={['Live IPO GMP and subscription','IPO dates and company insights','Historical metal prices and calculators']} href="/ipo" cta="Explore IPOs & Metals" preview="markets" reverse /></div></div></section>

    <section className="bg-gradient-to-r from-sky-50 to-emerald-50 py-10 dark:from-sky-950/20 dark:to-emerald-950/20"><div className="container mx-auto"><SectionHeading title="How WeeStox helps you decide" copy="A simple path from discovery to confident, ethical investing." /><div className="mt-7 grid items-center gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr]"><DecisionFlow number="1" title="Discover opportunities" copy="Find ideas across stocks, IPOs, metals and Islamic wealth tools." type="search" /><ArrowRight className="mx-auto hidden h-5 w-5 text-sky-500 md:block" /><DecisionFlow number="2" title="Analyse the full picture" copy="Explore charts, ratios, GMP and Shariah compliance in one place." type="analysis" /><ArrowRight className="mx-auto hidden h-5 w-5 text-sky-500 md:block" /><DecisionFlow number="3" title="Decide with ethical clarity" copy="Use transparent data and methodology aligned with your values." type="decision" /></div></div></section>

    <section className="py-12"><div className="container mx-auto"><SectionHeading title="A platform you can trust" copy="Built on ethical standards, transparent methodology and reliable data." /><div className="mt-8 grid items-center gap-5 lg:grid-cols-[220px_1fr]"><div className="flex items-center gap-4"><div className="flex h-24 w-24 shrink-0 flex-col items-center justify-center rounded-full border-[8px] border-emerald-500"><strong className="text-lg">4/4</strong><span className="text-[9px] text-slate-500">criteria</span></div><div><strong className="text-sm">AAOIFI Standard No. 21</strong><p className="mt-1 text-[10px] leading-4 text-slate-500">Shariah screening based on recognized financial criteria.</p></div></div><div className="grid gap-3 sm:grid-cols-3"><TrustCard icon={<FileSearch />} title="Transparent calculations" copy="Clear methodology you can verify." /><TrustCard icon={<PieChart />} title="Multiple market tools" copy="Stocks, IPOs, metals and Islamic wealth." /><TrustCard icon={<BarChart3 />} title="Live and historical data" copy="Reliable context for informed decisions." /></div></div></div></section>

    <section className="border-y border-slate-200 bg-slate-50/70 py-12 dark:border-slate-800 dark:bg-slate-900/30"><div className="container mx-auto"><div className="flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">Learn before you invest</h2><p className="mt-1 text-xs text-slate-500">Insights and guides for smarter, more ethical decisions.</p></div><Link href="/about" className="text-xs font-bold text-sky-600">View all articles <ArrowRight className="inline h-3 w-3" /></Link></div><div className="mt-6 grid gap-4 md:grid-cols-3"><Article icon={<LineChart />} tag="Stocks" title="Stock analysis basics" copy="Key ratios every investor should understand." /><Article icon={<Rocket />} tag="IPOs" title="Understanding IPO GMP" copy="What it means and how to use it wisely." /><Article icon={<Coins />} tag="Metals" title="Gold purity and Zakat" copy="A complete beginner’s guide." /></div></div></section>

    <ReviewMarquee />

    <section className="border-y border-slate-200 bg-slate-50/70 py-12 dark:border-slate-800 dark:bg-slate-900/30"><div className="container mx-auto max-w-5xl"><SectionHeading title="Frequently asked questions" copy="Quick answers about WeeStox and its market tools." /><div className="mt-7 divide-y divide-slate-200 overflow-hidden rounded-2xl border border-slate-200 bg-white px-5 dark:divide-slate-800 dark:border-slate-800 dark:bg-slate-900">{[
      ['What is WeeStox?', 'WeeStox combines stock research, IPO intelligence, precious-metal tracking and Islamic wealth tools in one platform.'],
      ['Is the Shariah screening based on AAOIFI standards?', 'Yes. The screening presents the applicable AAOIFI Standard No. 21 criteria and the underlying calculation values.'],
      ['Do you provide real-time data?', 'Availability and delay depend on the market and source. Every product identifies its latest update time.'],
      ['Can I use WeeStox for IPO research and GMP tracking?', 'Yes. IPO pages include GMP history, subscription, dates, allotment status, fundamentals and Shariah analysis when available.'],
      ['Which precious metals are covered?', 'The platform covers gold, silver and platinum with city rates, historical trends and calculators.'],
    ].map(([question, answer]) => <details key={question} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between text-sm font-bold">{question}<ChevronRight className="h-4 w-4 transition-transform group-open:rotate-90" /></summary><p className="mt-3 max-w-3xl text-xs leading-5 text-slate-500">{answer}</p></details>)}</div></div></section>

    <section className="py-12"><div className="container mx-auto"><div className="flex flex-col items-start justify-between gap-6 rounded-3xl bg-gradient-to-r from-sky-100 to-blue-50 px-7 py-9 dark:from-sky-950 dark:to-slate-900 md:flex-row md:items-center"><div><h2 className="text-2xl font-black text-slate-950 dark:text-white">Build wealth with clarity.</h2><p className="mt-2 text-xs text-slate-600 dark:text-slate-300">Access stocks, IPOs, metals and Islamic wealth tools in one trusted platform.</p></div><div className="flex flex-wrap gap-3"><Link href="/stocks" className="rounded-lg bg-sky-600 px-5 py-3 text-xs font-bold text-white">Launch Stock Screener</Link><Link href="/about" className="rounded-lg border border-sky-300 bg-white px-5 py-3 text-xs font-bold text-sky-700 dark:bg-slate-900">Explore All Tools</Link></div></div></div></section>
  </main>;
}

function MiniChart({ color }: { color: string }) { return <svg viewBox="0 0 150 56" className="h-14 w-36"><path d="M3 49 L18 40 L31 43 L46 27 L59 32 L72 20 L88 25 L101 14 L117 18 L132 8 L147 11" fill="none" stroke={color} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></svg>; }
function TrustMini({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="flex items-center gap-2 rounded-xl border border-white/70 bg-white/60 p-2 text-[9px] font-bold text-slate-600 shadow-sm dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-300"><span className="text-sky-600 [&>svg]:h-4 [&>svg]:w-4">{icon}</span>{title}</div>; }
const tones = { sky:'bg-sky-100 text-sky-600', rose:'bg-rose-100 text-rose-600', amber:'bg-amber-100 text-amber-600', emerald:'bg-emerald-100 text-emerald-600' } as const;
function CategoryLink({ href, icon, title, note, tone }: { href:string; icon:React.ReactNode; title:string; note:string; tone:keyof typeof tones }) { return <Link href={href} className="group flex items-center gap-3 rounded-xl border border-slate-200 p-3 hover:border-sky-300 dark:border-slate-800"><span className={`rounded-lg p-2 ${tones[tone]} [&>svg]:h-4 [&>svg]:w-4`}>{icon}</span><span className="min-w-0"><strong className="block text-xs">{title}</strong><span className="block truncate text-[9px] text-slate-500">{note}</span></span><ChevronRight className="ml-auto h-4 w-4 text-slate-400 group-hover:text-sky-600" /></Link>; }
function SectionHeading({ eyebrow, title, copy }: { eyebrow?:string; title:string; copy:string }) { return <div className="mx-auto max-w-2xl text-center">{eyebrow && <span className="text-[9px] font-bold uppercase tracking-[0.18em] text-sky-600">{eyebrow}</span>}<h2 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">{title}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{copy}</p></div>; }
function ProductCard({ href, icon, title, copy, items, preview, tone }: { href:string; icon:React.ReactNode; title:string; copy:string; items:string[]; preview:string; tone:keyof typeof tones }) { return <article className={`${card} flex min-h-80 flex-col p-5`}><span className={`w-fit rounded-xl p-2.5 ${tones[tone]} [&>svg]:h-5 [&>svg]:w-5`}>{icon}</span><h3 className="mt-4 text-base font-black">{title}</h3><p className="mt-2 text-[11px] leading-5 text-slate-500">{copy}</p><ul className="mt-4 space-y-2">{items.map((item) => <li key={item} className="flex items-center gap-2 text-[10px]"><Check className="h-3 w-3 text-emerald-500" />{item}</li>)}</ul><div className="mt-auto rounded-xl border border-slate-200 bg-slate-50 p-3 text-xs font-bold dark:border-slate-800 dark:bg-slate-950">{preview}</div><Link href={href} className="mt-3 inline-flex items-center justify-center gap-2 rounded-lg bg-sky-600 px-4 py-2.5 text-[10px] font-bold text-white">Explore {title} <ArrowRight className="h-3 w-3" /></Link></article>; }
function Showcase({ title, copy, bullets, href, cta, preview, reverse }: { title:string; copy:string; bullets:string[]; href:string; cta:string; preview:'stock'|'markets'; reverse?:boolean }) { return <div className={`grid items-center gap-8 lg:grid-cols-2 ${reverse ? 'lg:[&>*:first-child]:order-2' : ''}`}><div><h3 className="text-xl font-black">{title}</h3><p className="mt-3 max-w-xl text-xs leading-5 text-slate-500">{copy}</p><ul className="mt-5 space-y-2">{bullets.map((item) => <li key={item} className="flex items-center gap-2 text-xs"><Check className="h-3.5 w-3.5 text-emerald-500" />{item}</li>)}</ul><Link href={href} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-sky-600 px-5 py-3 text-xs font-bold text-white">{cta}<ArrowRight className="h-3 w-3" /></Link></div>{preview === 'stock' ? <StockPreview /> : <MarketPreview />}</div>; }
function StockPreview() { return <div className={`${card} p-5`}><div className="flex items-start justify-between"><div><span className="text-[9px] text-slate-400">NSE</span><h4 className="font-black">HDFC Bank Ltd.</h4><strong className="text-xl">₹1,640.15</strong></div><span className="rounded-lg bg-emerald-100 px-3 py-2 text-[10px] font-bold text-emerald-700">Shariah Compliant</span></div><div className="mt-5 grid gap-4 sm:grid-cols-[1.45fr_1fr]"><div className="rounded-xl bg-sky-50 p-3 dark:bg-sky-950/30"><MiniChart color="#0284c7" /><div className="mt-2 flex justify-between text-[9px] text-slate-500"><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span></div></div><div className="grid grid-cols-2 gap-2"><SmallMetric label="P/E" value="19.8" /><SmallMetric label="Market cap" value="₹11.9T" /><SmallMetric label="ROE" value="16.4%" /><SmallMetric label="Growth" value="+14.2%" /></div></div></div>; }
function MarketPreview() { return <div className="grid gap-3 sm:grid-cols-2"><div className={`${card} p-4`}><div className="flex justify-between text-xs font-black"><span>Upcoming IPOs</span><Link href="/ipo" className="text-sky-600">View all</Link></div>{['Tata Technologies','Ola Electric','Hyundai India'].map((name,index)=><div key={name} className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3 text-[10px] dark:border-slate-800"><span>{name}</span><b className="text-rose-600">+{12-index*4}%</b></div>)}</div><div className={`${card} p-4`}><div className="flex items-center justify-between"><b className="text-xs">Gold 24K</b><Coins className="h-4 w-4 text-amber-500" /></div><strong className="mt-4 block text-xl">₹73,482</strong><MiniChart color="#f59e0b" /><Link href="/gold" className="mt-2 block text-[10px] font-bold text-sky-600">Open metals desk →</Link></div></div>; }
function SmallMetric({label,value}:{label:string;value:string}) { return <div className="rounded-lg bg-slate-50 p-2 dark:bg-slate-950"><span className="block text-[8px] uppercase text-slate-400">{label}</span><b className="text-xs">{value}</b></div>; }
function DecisionFlow({number,title,copy,type}:{number:string;title:string;copy:string;type:'search'|'analysis'|'decision'}) { return <div><div className="mb-2 flex items-center gap-2"><span className={`flex h-6 w-6 items-center justify-center rounded-full text-[10px] font-black text-white ${type === 'decision' ? 'bg-emerald-500' : 'bg-sky-600'}`}>{number}</span><h3 className="text-xs font-black">{title}</h3></div><div className={`${card} h-24 p-3`}>{type === 'search' && <><div className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-[8px] text-slate-400 dark:border-slate-700"><Search className="h-3 w-3" />Search stocks, IPOs or tools...</div><div className="mt-2 flex gap-1 text-[7px]"><span className="rounded bg-slate-100 px-2 py-1 dark:bg-slate-800">RELIANCE</span><span className="rounded bg-slate-100 px-2 py-1 dark:bg-slate-800">Gold 24K</span><span className="rounded bg-slate-100 px-2 py-1 dark:bg-slate-800">Upcoming IPOs</span></div></>}{type === 'analysis' && <><div className="flex gap-4 border-b border-slate-200 pb-1 text-[7px] dark:border-slate-700"><b className="text-sky-600">Price</b><span>Financials</span><span>Shariah</span><span>News</span></div><svg viewBox="0 0 220 44" className="mt-1 h-11 w-full"><polyline points="2,38 24,32 45,34 66,25 88,28 112,18 133,22 154,11 177,15 218,4" fill="none" stroke="#3b82f6" strokeWidth="2" /></svg></>}{type === 'decision' && <div className="flex h-full flex-col items-center justify-center"><span className="rounded-lg bg-emerald-100 px-4 py-2 text-[9px] font-black text-emerald-700">✓ Shariah Compliant</span><span className="mt-2 rounded-md bg-sky-600 px-4 py-1.5 text-[8px] font-bold text-white">Add to Watchlist</span></div>}</div><p className="mt-2 text-[9px] leading-4 text-slate-500">{copy}</p></div>; }
function TrustCard({icon,title,copy}:{icon:React.ReactNode;title:string;copy:string}) { return <div className="flex items-start gap-3 rounded-xl border border-slate-200 p-4 dark:border-slate-800"><span className="rounded-lg bg-sky-100 p-2 text-sky-600 [&>svg]:h-4 [&>svg]:w-4">{icon}</span><div><b className="text-xs">{title}</b><p className="mt-1 text-[9px] leading-4 text-slate-500">{copy}</p></div></div>; }
function Article({icon,tag,title,copy}:{icon:React.ReactNode;tag:string;title:string;copy:string}) { return <article className={`${card} flex items-center gap-4 p-4`}><span className="rounded-xl bg-sky-100 p-3 text-sky-600 [&>svg]:h-5 [&>svg]:w-5">{icon}</span><div><span className="text-[8px] font-bold uppercase tracking-wider text-sky-600">{tag}</span><h3 className="mt-1 text-sm font-black">{title}</h3><p className="mt-1 text-[10px] text-slate-500">{copy}</p><span className="mt-2 block text-[9px] font-bold text-sky-600">5 min read →</span></div></article>; }
const reviews = [
  ['AK','The Shariah audit makes every pass and threshold easy to understand.','Stock research'],['PS','IPO GMP, allotment and subscription data are much easier to follow.','IPO tracking'],['FM','Metals and Zakat tools bring my research into one clear workflow.','Islamic wealth'],['RK','The stock detail layout gives me the important numbers without confusion.','Long-term investing'],['SA','I can compare valuations, growth and risks without opening several sites.','Fundamentals'],['NM','Gold and silver city rates are presented clearly and update quickly.','Precious metals'],['HI','The compliance methodology is transparent instead of showing only a badge.','Shariah screening'],['VR','Delivery and ownership charts help me understand conviction better.','Trading'],['AZ','The Zakat calculator makes the Nisab calculation simple to verify.','Zakat'],['MJ','The IPO pages combine the dates, GMP and company research I need.','IPO research'],['SK','Search and navigation make it easy to move between different markets.','Platform'],['TA','The page feels useful for both active trading and long-term research.','Market research'],
] as const;
function ReviewMarquee() { const items=[...reviews,...reviews]; return <section className="overflow-hidden py-12"><div className="container mx-auto flex items-end justify-between gap-4"><div><h2 className="text-2xl font-black">Community feedback</h2><p className="mt-1 text-xs text-slate-500">What investors value across WeeStox tools.</p></div><a href="mailto:care@weestox.com?subject=WeeStox%20feedback" className="rounded-lg border border-sky-300 px-4 py-2 text-xs font-bold text-sky-700 dark:border-sky-800 dark:text-sky-300">Share your feedback</a></div><div className="mt-7 overflow-hidden"><div className="flex w-max gap-4 animate-ticker">{items.map(([initials,text,category],index)=><article key={`${initials}-${index}`} className={`${card} w-[340px] shrink-0 p-5`}><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-sky-100 text-xs font-black text-sky-700">{initials}</span><span className="text-amber-500">★★★★★</span></div><p className="mt-4 text-xs leading-5 text-slate-600 dark:text-slate-300">“{text}”</p><span className="mt-4 block text-[9px] font-bold uppercase tracking-wide text-slate-400">{category}</span></article>)}</div></div></section>; }
