import type { Metadata } from 'next';
import JsonLd from '@/components/seo/JsonLd';
import {
  getBreadcrumbSchema,
  getFaqSchema,
  getSoftwareAppSchema,
} from '@/components/seo/siteSchemas';

export const metadata: Metadata = {
  title: 'Zakat & Nisab Calculator Online (Gold & Silver Benchmark)',
  description:
    'Calculate your exact annual Zakat obligation across cash, savings, gold, silver, equities, and trade assets with live Nisab benchmarks and automated dividend purification.',
  keywords: [
    'zakat calculator india',
    'nisab silver value today',
    'gold nisab calculator',
    'zakat on shares and stocks',
    'dividend purification calculator',
    'aaoifi zakat guidelines',
    'islamic wealth calculation',
  ],
  alternates: {
    canonical: '/zakat',
  },
  openGraph: {
    title: 'Zakat & Nisab Calculator Online (Gold & Silver Benchmark) | WeeStox',
    description:
      'Calculate your exact annual Zakat obligation across cash, gold, silver, equities, and trade assets with live Nisab benchmarks and purification breakdown.',
    url: '/zakat',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Zakat & Nisab Calculator Online | WeeStox',
    description:
      'Calculate your annual Zakat obligation with live Nisab benchmarks and dividend purification.',
  },
};

const ZAKAT_FAQS = [
  {
    question: 'What is the rate of Zakat in Islam?',
    answer:
      'The standard Zakat rate on liquid wealth, cash, gold, silver, and business inventory held for one full lunar year (Hawl) above the Nisab threshold is 2.5% (one fortieth).',
  },
  {
    question: 'What is the Nisab benchmark for Zakat?',
    answer:
      'Nisab is the minimum qualifying wealth threshold. In classical Islamic jurisprudence, it is defined as 85 grams of 24K gold or 595 grams of pure silver. Today, scholars recommend the silver Nisab to benefit more recipients in need.',
  },
  {
    question: 'How do I calculate Zakat on stock investments?',
    answer:
      'For short-term trading stocks, Zakat is due on the full current market value (2.5%). For long-term dividend-yielding investments, many scholars calculate Zakat on the proportional liquid/trade assets of the underlying company or 2.5% on dividends.',
  },
  {
    question: 'What is dividend purification in Shariah investing?',
    answer:
      'Dividend purification is the process of identifying and donating the impermissible interest or non-compliant revenue percentage generated by a compliant company, ensuring your wealth remains 100% pure.',
  },
];

export default function ZakatLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const softwareSchema = getSoftwareAppSchema({
    name: 'WeeStox Zakat & Purification Engine',
    description:
      'Institutional Zakat calculator with live gold/silver Nisab benchmark valuation and automated dividend purification.',
    applicationCategory: 'FinanceApplication',
    path: '/zakat',
  });
  const faqSchema = getFaqSchema(ZAKAT_FAQS);
  const breadcrumbs = getBreadcrumbSchema([
    { name: 'Home', path: '/' },
    { name: 'Zakat & Purification', path: '/zakat' },
  ]);

  return (
    <>
      <JsonLd data={[softwareSchema, faqSchema, breadcrumbs]} />
      {children}
    </>
  );
}
