import { StockItem } from './types';

export const mockStocksData: StockItem[] = [
  {
    id: 'tcs',
    symbol: 'TCS',
    name: 'Tata Consultancy Services Ltd.',
    exchange: 'NSE & BSE',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    price: 4124.50,
    change: 48.20,
    changePercent: 1.18,
    marketCapCr: 1492300,
    marketCapCategory: 'Large Cap',
    halalScore: 98,
    complianceStatus: 'compliant',
    statusReason: 'Flawless Shariah compliance: Zero interest-bearing debt, purely ethical enterprise IT services, and sub-0.5% interest revenue from liquid bank deposits.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.12,
      nonHalalRevenueSource: 'Interest on corporate cash reserves & fixed deposits',
      debtRatioPercent: 0.0,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 6.8,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 14.2,
      purificationPercent: 0.15,
    },
    fundamentals: {
      peRatio: 30.4,
      pbRatio: 14.8,
      roePercent: 48.2,
      rocePercent: 62.1,
      debtToEquity: 0.0,
      freeCashFlowCr: 42100,
      dividendYield: 1.82,
      week52High: 4585.90,
      week52Low: 3313.00,
    },
  },
  {
    id: 'infy',
    symbol: 'INFY',
    name: 'Infosys Limited',
    exchange: 'NSE & BSE',
    sector: 'Information Technology',
    industry: 'IT Services & Consulting',
    price: 1892.40,
    change: 22.80,
    changePercent: 1.22,
    marketCapCr: 785600,
    marketCapCategory: 'Large Cap',
    halalScore: 96,
    complianceStatus: 'compliant',
    statusReason: 'Debt-free balance sheet with premier corporate governance. Financial screening comfortably meets AAOIFI guidelines.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.25,
      nonHalalRevenueSource: 'Treasury yields on sovereign and commercial deposits',
      debtRatioPercent: 0.0,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 8.4,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 18.6,
      purificationPercent: 0.28,
    },
    fundamentals: {
      peRatio: 28.1,
      pbRatio: 9.6,
      roePercent: 32.5,
      rocePercent: 41.8,
      debtToEquity: 0.0,
      freeCashFlowCr: 21500,
      dividendYield: 2.15,
      week52High: 1991.45,
      week52Low: 1358.35,
    },
  },
  {
    id: 'sunpharma',
    symbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical Industries Ltd.',
    exchange: 'NSE & BSE',
    sector: 'Healthcare & Pharma',
    industry: 'Pharmaceuticals',
    price: 1845.60,
    change: -12.40,
    changePercent: -0.67,
    marketCapCr: 442800,
    marketCapCategory: 'Large Cap',
    halalScore: 92,
    complianceStatus: 'compliant',
    statusReason: 'Core pharmaceutical formulations. Total debt remains strictly below 5% of total enterprise capitalization.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.65,
      nonHalalRevenueSource: 'Interest on international cash sweeps',
      debtRatioPercent: 4.8,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 11.2,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 21.4,
      purificationPercent: 0.72,
    },
    fundamentals: {
      peRatio: 38.2,
      pbRatio: 5.7,
      roePercent: 16.4,
      rocePercent: 18.9,
      debtToEquity: 0.08,
      freeCashFlowCr: 9800,
      dividendYield: 0.85,
      week52High: 1960.00,
      week52Low: 1110.10,
    },
  },
  {
    id: 'titan',
    symbol: 'TITAN',
    name: 'Titan Company Limited',
    exchange: 'NSE & BSE',
    sector: 'Consumer Discretionary',
    industry: 'Luxury Goods & Jewellery',
    price: 3480.15,
    change: 34.60,
    changePercent: 1.00,
    marketCapCr: 308900,
    marketCapCategory: 'Large Cap',
    halalScore: 90,
    complianceStatus: 'compliant',
    statusReason: 'Physical jewellery & precision watches business. Spot physical delivery compliant with Shariah gold exchange rules.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.40,
      nonHalalRevenueSource: 'Deposit interest & minor customer finance commissions',
      debtRatioPercent: 7.2,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 5.1,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 8.9,
      purificationPercent: 0.45,
    },
    fundamentals: {
      peRatio: 82.5,
      pbRatio: 26.2,
      roePercent: 33.1,
      rocePercent: 28.6,
      debtToEquity: 0.85,
      freeCashFlowCr: 3200,
      dividendYield: 0.32,
      week52High: 3886.95,
      week52Low: 3055.65,
    },
  },
  {
    id: 'cipla',
    symbol: 'CIPLA',
    name: 'Cipla Limited',
    exchange: 'NSE & BSE',
    sector: 'Healthcare & Pharma',
    industry: 'Pharmaceuticals',
    price: 1582.30,
    change: 18.10,
    changePercent: 1.16,
    marketCapCr: 127800,
    marketCapCategory: 'Large Cap',
    halalScore: 94,
    complianceStatus: 'compliant',
    statusReason: 'Ethical respiratory & essential medication portfolio. Extremely low leverage ratio of 1.8% against market cap.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.38,
      nonHalalRevenueSource: 'Short-term debt fund earnings',
      debtRatioPercent: 1.8,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 14.1,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 19.8,
      purificationPercent: 0.40,
    },
    fundamentals: {
      peRatio: 26.8,
      pbRatio: 4.1,
      roePercent: 16.2,
      rocePercent: 22.4,
      debtToEquity: 0.04,
      freeCashFlowCr: 3600,
      dividendYield: 0.82,
      week52High: 1702.00,
      week52Low: 1132.00,
    },
  },
  {
    id: 'drreddy',
    symbol: 'DRREDDY',
    name: "Dr. Reddy's Laboratories Ltd.",
    exchange: 'NSE & BSE',
    sector: 'Healthcare & Pharma',
    industry: 'Pharmaceuticals',
    price: 6685.00,
    change: 41.50,
    changePercent: 0.62,
    marketCapCr: 111500,
    marketCapCategory: 'Large Cap',
    halalScore: 91,
    complianceStatus: 'compliant',
    statusReason: 'Pure pharmaceutical manufacturer with pristine compliance ratios and low reliance on external interest debt.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.52,
      nonHalalRevenueSource: 'Interest from domestic & foreign fixed deposits',
      debtRatioPercent: 3.4,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 9.8,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 22.1,
      purificationPercent: 0.58,
    },
    fundamentals: {
      peRatio: 20.1,
      pbRatio: 3.8,
      roePercent: 20.4,
      rocePercent: 24.1,
      debtToEquity: 0.12,
      freeCashFlowCr: 4100,
      dividendYield: 0.60,
      week52High: 7104.00,
      week52Low: 5212.00,
    },
  },
  {
    id: 'polycab',
    symbol: 'POLYCAB',
    name: 'Polycab India Limited',
    exchange: 'NSE & BSE',
    sector: 'Industrial & Manufacturing',
    industry: 'Cables & Electricals',
    price: 6420.75,
    change: 112.30,
    changePercent: 1.78,
    marketCapCr: 96500,
    marketCapCategory: 'Large Cap',
    halalScore: 89,
    complianceStatus: 'compliant',
    statusReason: 'Industrial wire & fast-moving electrical goods. Balance sheet maintains net-cash positioning.',
    isNifty50: false,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.31,
      nonHalalRevenueSource: 'Bank sweep deposit interest',
      debtRatioPercent: 2.1,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 8.9,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 16.4,
      purificationPercent: 0.35,
    },
    fundamentals: {
      peRatio: 51.2,
      pbRatio: 11.4,
      roePercent: 24.8,
      rocePercent: 31.2,
      debtToEquity: 0.05,
      freeCashFlowCr: 1450,
      dividendYield: 0.47,
      week52High: 7350.00,
      week52Low: 3812.00,
    },
  },
  {
    id: 'tataelxsi',
    symbol: 'TATAELXSI',
    name: 'Tata Elxsi Limited',
    exchange: 'NSE & BSE',
    sector: 'Information Technology',
    industry: 'Design & Engineering Services',
    price: 7850.00,
    change: -45.00,
    changePercent: -0.57,
    marketCapCr: 48900,
    marketCapCategory: 'Mid Cap',
    halalScore: 97,
    complianceStatus: 'compliant',
    statusReason: 'Completely debt-free software design & technology enterprise. High cash flow with minimal impermissible income.',
    isNifty50: false,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.19,
      nonHalalRevenueSource: 'Interest on mutual fund liquid instruments',
      debtRatioPercent: 0.0,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 12.8,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 15.2,
      purificationPercent: 0.22,
    },
    fundamentals: {
      peRatio: 61.4,
      pbRatio: 18.2,
      roePercent: 34.6,
      rocePercent: 44.5,
      debtToEquity: 0.0,
      freeCashFlowCr: 690,
      dividendYield: 0.89,
      week52High: 9200.00,
      week52Low: 6411.00,
    },
  },
  {
    id: 'tatamotors',
    symbol: 'TATAMOTORS',
    name: 'Tata Motors Limited',
    exchange: 'NSE & BSE',
    sector: 'Automotive',
    industry: 'Commercial & Passenger Vehicles',
    price: 994.25,
    change: -14.10,
    changePercent: -1.40,
    marketCapCr: 365400,
    marketCapCategory: 'Large Cap',
    halalScore: 68,
    complianceStatus: 'doubtful',
    statusReason: 'Under Review: Business activity is fully halal, but consolidated interest debt (primarily JLR financing) hovers near the 33% AAOIFI ceiling (currently ~31.8%).',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 1.45,
      nonHalalRevenueSource: 'Automotive retail financing affiliate income',
      debtRatioPercent: 31.8,
      debtRatioStatus: 'pass', // Borderline (<33%)
      cashAndSecuritiesRatioPercent: 14.5,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 24.1,
      purificationPercent: 1.60,
    },
    fundamentals: {
      peRatio: 10.4,
      pbRatio: 3.8,
      roePercent: 38.1,
      rocePercent: 21.2,
      debtToEquity: 1.15,
      freeCashFlowCr: 26800,
      dividendYield: 0.60,
      week52High: 1179.05,
      week52Low: 608.00,
    },
  },
  {
    id: 'airtel',
    symbol: 'BHARTIARTL',
    name: 'Bharti Airtel Limited',
    exchange: 'NSE & BSE',
    sector: 'Telecommunications',
    industry: 'Telecom Services',
    price: 1540.80,
    change: 15.60,
    changePercent: 1.02,
    marketCapCr: 889200,
    marketCapCategory: 'Large Cap',
    halalScore: 64,
    complianceStatus: 'doubtful',
    statusReason: 'Telecom operations are halal, but long-term spectrum dues and lease debt place debt ratio at ~32.4%, right on the AAOIFI compliance border.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 1.20,
      nonHalalRevenueSource: 'Airtel Payments Bank interest & treasury sweeps',
      debtRatioPercent: 32.4,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 6.2,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 8.5,
      purificationPercent: 1.35,
    },
    fundamentals: {
      peRatio: 64.2,
      pbRatio: 8.9,
      roePercent: 15.8,
      rocePercent: 14.6,
      debtToEquity: 2.12,
      freeCashFlowCr: 31200,
      dividendYield: 0.52,
      week52High: 1622.00,
      week52Low: 890.00,
    },
  },
  {
    id: 'hdfcbank',
    symbol: 'HDFCBANK',
    name: 'HDFC Bank Limited',
    exchange: 'NSE & BSE',
    sector: 'Banking & Financial Services',
    industry: 'Commercial Banking',
    price: 1645.10,
    change: -8.30,
    changePercent: -0.50,
    marketCapCr: 1251000,
    marketCapCategory: 'Large Cap',
    halalScore: 12,
    complianceStatus: 'non_compliant',
    statusReason: 'Strictly Non-Compliant: Core revenue model is derived from conventional interest-based lending (Riba) and debt instruments.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'fail',
      nonHalalRevenuePercent: 84.5,
      nonHalalRevenueSource: 'Interest spread on commercial and retail loans',
      debtRatioPercent: 88.0,
      debtRatioStatus: 'fail',
      cashAndSecuritiesRatioPercent: 45.2,
      cashRatioStatus: 'fail',
      receivablesRatioPercent: 78.0,
      purificationPercent: 100.0,
    },
    fundamentals: {
      peRatio: 18.5,
      pbRatio: 2.8,
      roePercent: 16.9,
      rocePercent: 12.1,
      debtToEquity: 7.4,
      freeCashFlowCr: 0,
      dividendYield: 1.18,
      week52High: 1794.00,
      week52Low: 1363.55,
    },
  },
  {
    id: 'itc',
    symbol: 'ITC',
    name: 'ITC Limited',
    exchange: 'NSE & BSE',
    sector: 'Consumer Goods (FMCG)',
    industry: 'Cigarettes & FMCG',
    price: 504.60,
    change: 3.20,
    changePercent: 0.64,
    marketCapCr: 631000,
    marketCapCategory: 'Large Cap',
    halalScore: 28,
    complianceStatus: 'non_compliant',
    statusReason: 'Non-Compliant: Tobacco and cigarette manufacturing generates over 38% of revenue and >70% of operating profits, well exceeding the 5% threshold.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'fail',
      nonHalalRevenuePercent: 38.6,
      nonHalalRevenueSource: 'Tobacco & cigarette manufacturing operations',
      debtRatioPercent: 0.1,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 6.8,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 5.2,
      purificationPercent: 42.0,
    },
    fundamentals: {
      peRatio: 28.6,
      pbRatio: 8.8,
      roePercent: 29.5,
      rocePercent: 38.7,
      debtToEquity: 0.01,
      freeCashFlowCr: 16800,
      dividendYield: 2.72,
      week52High: 520.00,
      week52Low: 399.30,
    },
  },
  {
    id: 'bajajfinance',
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance Limited',
    exchange: 'NSE & BSE',
    sector: 'Banking & Financial Services',
    industry: 'Non-Banking Financial Company (NBFC)',
    price: 7120.00,
    change: -68.00,
    changePercent: -0.95,
    marketCapCr: 440200,
    marketCapCategory: 'Large Cap',
    halalScore: 15,
    complianceStatus: 'non_compliant',
    statusReason: 'Non-Compliant: NBFC operations revolve exclusively around interest-bearing consumer lending, credit cards, and interest income.',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'fail',
      nonHalalRevenuePercent: 88.2,
      nonHalalRevenueSource: 'Interest charged on consumer loans & EMI financing',
      debtRatioPercent: 72.4,
      debtRatioStatus: 'fail',
      cashAndSecuritiesRatioPercent: 28.0,
      cashRatioStatus: 'fail',
      receivablesRatioPercent: 85.0,
      purificationPercent: 100.0,
    },
    fundamentals: {
      peRatio: 29.4,
      pbRatio: 5.6,
      roePercent: 22.1,
      rocePercent: 14.8,
      debtToEquity: 3.8,
      freeCashFlowCr: 0,
      dividendYield: 0.51,
      week52High: 7850.00,
      week52Low: 6160.00,
    },
  },
  {
    id: 'asianpaint',
    symbol: 'ASIANPAINT',
    name: 'Asian Paints Limited',
    exchange: 'NSE & BSE',
    sector: 'Consumer Goods & Materials',
    industry: 'Paints & Coatings',
    price: 3120.40,
    change: 28.10,
    changePercent: 0.91,
    marketCapCr: 299200,
    marketCapCategory: 'Large Cap',
    halalScore: 93,
    complianceStatus: 'compliant',
    statusReason: 'Ethical manufacturing of architectural paints and waterproofing products. High liquidity with minimal interest debt (3.1%).',
    isNifty50: true,
    lastUpdated: '10 Sep 2026',
    shariah: {
      businessActivityStatus: 'pass',
      nonHalalRevenuePercent: 0.42,
      nonHalalRevenueSource: 'Treasury yields on commercial fixed deposits',
      debtRatioPercent: 3.1,
      debtRatioStatus: 'pass',
      cashAndSecuritiesRatioPercent: 8.2,
      cashRatioStatus: 'pass',
      receivablesRatioPercent: 16.8,
      purificationPercent: 0.48,
    },
    fundamentals: {
      peRatio: 56.4,
      pbRatio: 16.8,
      roePercent: 29.2,
      rocePercent: 37.1,
      debtToEquity: 0.12,
      freeCashFlowCr: 4100,
      dividendYield: 0.98,
      week52High: 3422.00,
      week52Low: 2750.00,
    },
  },
];
