import fs from 'node:fs';
fs.writeFileSync('features/metals/components/SmartMetalCalculator.tsx', `
'use client';
import { useState } from 'react';
import { Calculator, ArrowRight } from 'lucide-react';
import Link from 'next/link';
import type { Metal } from '../types';
import { purchaseEstimate, nonNegative } from '@/lib/calculations';
const currency=(value:number)=>value.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
export function SmartMetalCalculator({metal,cityName,prices}:{metal:Metal;cityName:string;prices:{'24K'?:number;'22K'?:number;'18K'?:number;perGram?:number}}) {
  const [purity,setPurity]=useState<'24K'|'22K'|'18K'>('22K');
  const [weight,setWeight]=useState(metal==='silver'?'100':'10');
  const [making,setMaking]=useState(0);
  const [tax,setTax]=useState(true);
  const rate=nonNegative(metal==='gold'?prices[purity]:prices.perGram);
  const result=purchaseEstimate(rate,nonNegative(weight),making,tax?3:0);
  return <section className="surface p-6"><div className="flex items-center gap-3 mb-5"><span className="tool-icon"><Calculator size={21}/></span><div><span className="eyebrow">PLAN YOUR PURCHASE</span><h2 className="text-lg mt-1">{cityName} {metal} calculator</h2></div></div>
    <div className="grid md:grid-cols-2 gap-6"><div className="space-y-5">{metal==='gold'&&<div><span className="form-label">Gold purity</span><div className="range-tabs">{(['24K','22K','18K'] as const).map(p=><button key={p} aria-pressed={purity===p} onClick={()=>setPurity(p)}>{p}</button>)}</div></div>}
      <div><label className="form-label" htmlFor="metal-weight">Weight in grams</label><input id="metal-weight" className="form-input" type="number" min="0.01" max="1000000000000" step="any" value={weight} onChange={e=>setWeight(e.target.value)} aria-invalid={weight!==''&&(!nonNegative(weight)||nonNegative(weight)===null)}/><div className="flex flex-wrap gap-2 mt-2">{[1,8,10,100,1000].map(w=><button className="weight-chip" key={w} onClick={()=>setWeight(String(w))} aria-pressed={Number(weight)===w}>{w===1000?'1 kg':w+' g'}</button>)}</div></div>
      <div><label className="form-label" htmlFor="making-charge">Making charges <span className="text-accent">{making}%</span></label><input id="making-charge" type="range" min="0" max="30" step="0.5" value={making} onChange={e=>setMaking(Number(e.target.value))} className="w-full accent-blue-600"/><p className="text-xs text-muted mt-1">Set the charge quoted by your seller.</p></div>
      <label className="flex items-center gap-2 text-xs text-body"><input type="checkbox" checked={tax} onChange={e=>setTax(e.target.checked)} className="accent-blue-600"/>Include 3% GST on metal + making charges</label>
    </div><div className="calculation-result"><span className="eyebrow">ESTIMATED PURCHASE COST</span><strong className="calculation-total">{result?currency(result.total):'—'}</strong><p className="text-xs text-muted">{rate?currency(rate)+' per gram · source rate':'A source rate is unavailable for this purity.'}</p>
      {result?<dl className="calculation-lines"><div><dt>Metal value</dt><dd>{currency(result.base)}</dd></div><div><dt>Making charges ({making}%)</dt><dd>{currency(result.making)}</dd></div><div><dt>{tax?'GST (3%)':'Tax excluded'}</dt><dd>{currency(result.tax)}</dd></div></dl>:<p className="notice mt-5">{rate?'Enter a valid weight greater than zero to calculate.':'Choose an available purity or check again later.'}</p>}
      <p className="text-[11px] text-muted leading-relaxed mt-5">Estimate only. Other seller charges are excluded. Unchecking GST excludes tax from this estimate; it does not imply an exemption. <a href="https://cbic-gst.gov.in/sectoral-faq.html" target="_blank" rel="noopener noreferrer" className="text-accent underline">GST reference</a>.</p>
    </div></div><Link href="/zakat" className="inline-flex items-center gap-2 text-xs text-accent mt-5">Calculate Zakat across your assets<ArrowRight size={14}/></Link>
  </section>;
}
`.trimStart());
fs.writeFileSync('app/zakat/page.tsx', `
'use client';
import { useState } from 'react';
import { Calculator, Wallet, ShieldCheck, RotateCcw } from 'lucide-react';
import { zakatEstimate, nonNegative } from '@/lib/calculations';
const fields=[{id:'cash',label:'Cash & bank balances',hint:'Money you own, excluding interest.'},{id:'gold',label:'Gold & silver value',hint:'Current value of qualifying holdings, in rupees.'},{id:'stocks',label:'Qualifying investments',hint:'Zakatable value according to your chosen method.'},{id:'business',label:'Business inventory & receivables',hint:'Qualifying stock and collectible amounts.'}] as const;
const empty={cash:'',gold:'',stocks:'',business:'',liabilities:''};
const currency=(value:number)=>value.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
export default function ZakatPage(){
  const [form,setForm]=useState(empty);const [basis,setBasis]=useState<'gold'|'silver'|'custom'>('silver');const [rate,setRate]=useState('');const [lunarYear,setLunarYear]=useState(false);
  const numbers=fields.map(f=>form[f.id]===''?0:nonNegative(form[f.id]));
  const liabilities=form.liabilities===''?0:nonNegative(form.liabilities);
  const rateValue=nonNegative(rate);const nisab=rateValue===null?null:rateValue*(basis==='gold'?85:basis==='silver'?595:1);
  const result=numbers.includes(null)||liabilities===null?null:zakatEstimate(numbers as number[],liabilities,nisab,lunarYear);
  const update=(id:keyof typeof empty,value:string)=>setForm(previous=>({...previous,[id]:value}));
  return <div className="container py-10 pb-16"><div className="page-heading"><div><span className="eyebrow">WEALTH WITH PURPOSE</span><h1>A little clarity. A meaningful contribution.</h1><p>Build a Zakat estimate with a clear breakdown of your assets and assumptions.</p></div><button className="btn btn-outline" onClick={()=>{setForm(empty);setRate('');setLunarYear(false);setBasis('silver')}}><RotateCcw size={14}/>Reset</button></div>
    <div className="wealth-grid"><div className="space-y-5"><section className="surface p-6"><h2 className="text-lg flex items-center gap-2 mb-2"><Wallet size={19} className="text-accent"/>Your qualifying assets</h2><p className="text-xs text-muted mb-6">Enter amounts in INR. Your entries stay in this page and are not sent to a server.</p><div className="grid sm:grid-cols-2 gap-5">{fields.map(f=><div key={f.id}><label className="form-label" htmlFor={f.id}>{f.label}</label><div className="money-input"><span>₹</span><input id={f.id} type="number" min="0" max="1000000000000" step="any" placeholder="0.00" value={form[f.id]} onChange={e=>update(f.id,e.target.value)} aria-invalid={form[f.id]!==''&&nonNegative(form[f.id])===null}/></div><p className="text-[11px] text-muted mt-2 leading-relaxed">{f.hint}</p></div>)}</div><div className="border-t border-line pt-5 mt-6"><label className="form-label" htmlFor="liabilities">Deductible immediate liabilities</label><div className="money-input"><span>₹</span><input id="liabilities" type="number" min="0" max="1000000000000" step="any" placeholder="0.00" value={form.liabilities} onChange={e=>update('liabilities',e.target.value)} aria-invalid={form.liabilities!==''&&liabilities===null}/></div><p className="text-[11px] text-muted mt-2">Include only liabilities deductible under the method you follow, not automatically the whole balance of a long-term loan.</p></div></section>
    <section className="surface p-6"><h2 className="text-lg flex items-center gap-2 mb-2"><ShieldCheck size={19} className="text-accent"/>Set your Nisab benchmark</h2><p className="text-xs text-muted mb-5">Choose your basis and enter a current rate, or use your own threshold.</p><div className="range-tabs mb-5">{(['silver','gold','custom'] as const).map(b=><button key={b} aria-pressed={basis===b} onClick={()=>{setBasis(b);setRate('')}}>{b==='silver'?'Silver · 595g':b==='gold'?'Gold · 85g':'Custom threshold'}</button>)}</div><label className="form-label" htmlFor="nisab-rate">{basis==='custom'?'Nisab threshold in INR':'Current pure '+basis+' rate per gram (INR)'}</label><div className="money-input"><span>₹</span><input id="nisab-rate" type="number" min="0.01" max="1000000000000" step="any" placeholder="Enter current value" value={rate} onChange={e=>setRate(e.target.value)}/></div><label className="flex gap-3 items-start mt-6 text-sm text-body leading-relaxed"><input type="checkbox" className="mt-1 accent-blue-600" checked={lunarYear} onChange={e=>setLunarYear(e.target.checked)}/><span>I confirm that the applicable lunar-year holding condition has been met.</span></label></section></div>
    <aside className="wealth-summary surface"><div className="flex items-center gap-2 text-accent mb-5"><Calculator size={20}/><span className="eyebrow">YOUR ESTIMATE</span></div><span className="text-xs text-muted">Estimated Zakat · 2.5%</span><strong className="calculation-total">{result?.amount!=null?currency(result.amount):'—'}</strong><p className="text-xs text-muted leading-relaxed">{!result?'Use valid, non-negative amounts.':!nisab?'Enter your Nisab benchmark to calculate.':!lunarYear?'Confirm the holding condition to calculate.':!result.eligible?'Your net assets are below the selected threshold.':'Based on the assets and assumptions entered.'}</p><dl className="calculation-lines"><div><dt>Total assets</dt><dd>{result?currency(result.gross):'—'}</dd></div><div><dt>Liabilities</dt><dd>{liabilities===null?'—':currency(liabilities)}</dd></div><div><dt>Net qualifying wealth</dt><dd>{result?currency(result.net):'—'}</dd></div><div><dt>Nisab threshold</dt><dd>{nisab?currency(nisab):'—'}</dd></div></dl><div className="notice mt-5"><strong className="text-ink">How it works</strong><p>When eligible: max(assets − deductible liabilities, 0) × 2.5%. Results update as you edit.</p></div><p className="text-[11px] text-muted leading-relaxed mt-5">This estimate uses a lunar-year method. Asset eligibility and deductions can vary; confirm your method with a qualified scholar. <a className="text-accent underline" href="https://islamic-relief.org/zakat-faq/" target="_blank" rel="noopener noreferrer">Read the Zakat guidance</a>.</p></aside></div>
  </div>;
}
`.trimStart());
