'use client';

import { useMemo, useState } from 'react';
import { formatSafePct } from '../utils/mappers';

type HoldingKey = 'promoter' | 'fii' | 'dii' | 'public';
type Filter = 'all' | HoldingKey;
type Frequency = 'annual' | 'quarterly';
type ViewMode = 'chart' | 'table';
type HoldingRow = { quarter: string; promoter: number | null; fii: number | null; dii: number | null; public: number | null; pledged?: number | null; num_shareholders?: number | null; top_institutions?: Array<{ name: string; category: string; holding_pct: number }> };

const categories: Array<{ key: HoldingKey; label: string; shortLabel: string; color: string; className: string }> = [
  { key: 'promoter', label: 'Promoters', shortLabel: 'Promoters', color: '#0284c7', className: 'bg-sky-600' },
  { key: 'fii', label: 'Foreign Institutions', shortLabel: 'FIIs', color: '#8b5cf6', className: 'bg-violet-500' },
  { key: 'dii', label: 'Domestic Institutions', shortLabel: 'DIIs', color: '#10b981', className: 'bg-emerald-500' },
  { key: 'public', label: 'Retail & Public', shortLabel: 'Public', color: '#f59e0b', className: 'bg-amber-500' },
];

function periodLabel(value: string, long = false) {
  const date = new Date(`${value.slice(0, 10)}T00:00:00`);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('en-IN', { month: long ? 'long' : 'short', year: 'numeric' });
}
function changeBetween(current: number | null | undefined, previous: number | null | undefined) { return current == null || previous == null ? null : Number((Number(current) - Number(previous)).toFixed(2)); }
function Trend({ value }: { value: number | null }) { if (value == null) return <span className="text-slate-400">—</span>; return <span className={`whitespace-nowrap font-bold ${value > 0 ? 'text-emerald-600' : value < 0 ? 'text-rose-600' : 'text-slate-500'}`}>{value > 0 ? '↑ ' : value < 0 ? '↓ ' : '— '}{Math.abs(value).toFixed(2)}%</span>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-slate-50/70 p-3 text-center dark:border-slate-800 dark:bg-slate-950/40"><strong className="block text-sm">{value}</strong><span className="text-[9px] text-slate-500">{label}</span></div>; }

export default function ShareholdingCharts({ rows }: { rows: HoldingRow[] }) {
  const quarterlyRows = useMemo(() => rows.filter((row) => categories.some((category) => row[category.key] != null)).sort((a, b) => b.quarter.localeCompare(a.quarter)), [rows]);
  const annualRows = useMemo(() => { const byYear = new Map<string, HoldingRow>(); quarterlyRows.forEach((row) => { const year = row.quarter.slice(0, 4); if (!byYear.has(year)) byYear.set(year, row); }); return Array.from(byYear.values()).sort((a, b) => b.quarter.localeCompare(a.quarter)); }, [quarterlyRows]);
  const [frequency, setFrequency] = useState<Frequency>('quarterly');
  const [view, setView] = useState<ViewMode>('chart');
  const [filter, setFilter] = useState<Filter>('all');
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);
  const [showAllHolders, setShowAllHolders] = useState(false);
  const selectedRows = frequency === 'annual' ? annualRows : quarterlyRows;
  const history = [...selectedRows].reverse();
  const latest = selectedRows[0]; const previous = selectedRows[1];
  if (!latest) return null;
  const visibleCategories = filter === 'all' ? categories : categories.filter((category) => category.key === filter);
  const visibleValues = visibleCategories.flatMap((category) => history.map((row) => Number(row[category.key] ?? 0)));
  const rawMin = visibleValues.length ? Math.min(...visibleValues) : 0; const rawMax = visibleValues.length ? Math.max(...visibleValues) : 1;
  const yMin = filter === 'all' ? 0 : Math.max(0, Math.floor(rawMin - 2)); const yMax = filter === 'all' ? Math.max(60, Math.ceil(rawMax / 10) * 10) : Math.max(yMin + 4, Math.ceil(rawMax + 2));
  const chart = { left: 42, right: 584, top: 18, bottom: 154 };
  const xAt = (index: number) => history.length > 1 ? chart.left + index / (history.length - 1) * (chart.right - chart.left) : (chart.left + chart.right) / 2;
  const yAt = (value: number | null) => chart.bottom - ((Number(value ?? 0) - yMin) / Math.max(1, yMax - yMin)) * (chart.bottom - chart.top);
  const points = (key: HoldingKey) => history.map((row, index) => `${xAt(index)},${yAt(row[key])}`).join(' ');
  const area = (key: HoldingKey) => `${chart.left},${chart.bottom} ${points(key)} ${chart.right},${chart.bottom}`;
  const ticks = Array.from({ length: 4 }, (_, index) => yMin + (yMax - yMin) * index / 3).reverse();
  const hovered = hoveredIndex == null ? null : history[hoveredIndex];
  const institutional = Number(latest.fii || 0) + Number(latest.dii || 0);
  const latestShareholders = rows.find((row) => row.num_shareholders != null)?.num_shareholders;
  const topInstitutions = latest.top_institutions || [];

  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50/70 p-2 dark:border-slate-800 dark:bg-slate-950/40"><div className="px-2"><strong className="block text-xs">{frequency === 'annual' ? 'Annual ownership snapshots' : 'Quarterly ownership history'}</strong><span className="text-[9px] text-slate-400">Latest valid period · {periodLabel(latest.quarter, true)}</span></div><div className="flex flex-wrap gap-2"><Toggle values={['annual', 'quarterly']} selected={frequency} onSelect={(item) => { setFrequency(item as Frequency); setHoveredIndex(null); }} /><Toggle values={['chart', 'table']} selected={view} dark onSelect={(item) => setView(item as ViewMode)} /></div></div>

    <div className="grid grid-cols-2 gap-1 rounded-xl border border-slate-200 p-2 sm:grid-cols-4 dark:border-slate-800">{categories.map((category) => { const value = latest[category.key]; const change = changeBetween(value, previous?.[category.key]); return <button type="button" key={category.key} onClick={() => { setFilter(filter === category.key ? 'all' : category.key); setView('chart'); }} className={`flex items-center gap-2.5 rounded-lg px-2.5 py-2 text-left transition ${filter === category.key ? 'bg-sky-50 ring-1 ring-sky-200 dark:bg-sky-950/30 dark:ring-sky-800' : 'hover:bg-slate-50 dark:hover:bg-slate-800/60'}`}><i className={`h-2.5 w-2.5 shrink-0 rounded-full ${category.className}`} /><span className="whitespace-nowrap text-[10px] font-bold text-slate-500">{category.shortLabel}</span><b className="whitespace-nowrap text-[10px] text-slate-900 dark:text-white">{formatSafePct(value, false)}</b><span className="text-[10px]"><Trend value={change} /></span></button>; })}</div>

    {view === 'chart' ? <div className="grid gap-4 lg:grid-cols-[480px_minmax(0,1fr)]">
      <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><h3 className="mb-4 text-xs font-black">Ownership distribution</h3><div className="grid grid-cols-[170px_minmax(0,1fr)] items-center gap-4"><div className="relative mx-auto h-40 w-40 rounded-full transition-transform duration-200 hover:scale-[1.03]" style={{ background: `conic-gradient(#0284c7 0 ${Number(latest.promoter || 0)}%, #8b5cf6 ${Number(latest.promoter || 0)}% ${Number(latest.promoter || 0) + Number(latest.fii || 0)}%, #10b981 ${Number(latest.promoter || 0) + Number(latest.fii || 0)}% ${Number(latest.promoter || 0) + Number(latest.fii || 0) + Number(latest.dii || 0)}%, #f59e0b ${Number(latest.promoter || 0) + Number(latest.fii || 0) + Number(latest.dii || 0)}% 100%)` }}><div className="absolute inset-5 flex flex-col items-center justify-center rounded-full bg-white dark:bg-slate-900"><strong className="text-sm">{periodLabel(latest.quarter)}</strong><span className="text-[9px] text-slate-400">Latest holding</span></div></div><div className="space-y-1.5">{categories.map((category) => <button type="button" key={category.key} onClick={() => setFilter(filter === category.key ? 'all' : category.key)} className={`grid w-full grid-cols-[10px_minmax(0,1fr)_auto] items-center gap-2 rounded-lg border px-2 py-2 text-[10px] ${filter === category.key ? 'border-sky-300 bg-sky-50 dark:border-sky-800 dark:bg-sky-950/30' : 'border-transparent hover:bg-slate-50 dark:hover:bg-slate-800/50'}`}><i className={`h-2.5 w-2.5 rounded-full ${category.className}`} /><span className="truncate text-left text-slate-500">{category.label}</span><b>{formatSafePct(latest[category.key], false)}</b></button>)}</div></div></div>
      <div className="min-w-0 rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div className="mb-2 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xs font-black">Category trends</h3><p className="text-[9px] text-slate-400">Hover over a period for exact holdings</p></div><div className="flex rounded-lg border border-slate-200 bg-slate-50 p-1 dark:border-slate-700 dark:bg-slate-950">{(['all', ...categories.map((category) => category.key)] as Filter[]).map((key) => <button type="button" key={key} onClick={() => setFilter(key)} className={`rounded-md px-2.5 py-1 text-[9px] font-bold ${filter === key ? 'bg-sky-600 text-white shadow-sm' : 'text-slate-500 hover:text-sky-600'}`}>{key === 'all' ? 'All' : categories.find((category) => category.key === key)?.shortLabel}</button>)}</div></div><div className="relative"><svg viewBox="0 0 600 184" className="h-48 w-full overflow-visible" role="img" aria-label={`${visibleCategories.map((category) => category.label).join(', ')} shareholding history`} onMouseLeave={() => setHoveredIndex(null)}>{ticks.map((value) => <g key={value}><line x1={chart.left} x2={chart.right} y1={yAt(value)} y2={yAt(value)} stroke="currentColor" className="text-slate-200 dark:text-slate-800" strokeDasharray="3 3" /><text x="4" y={yAt(value) + 3} className="fill-slate-400 text-[8px]">{value.toFixed(filter === 'all' ? 0 : 1)}%</text></g>)}{visibleCategories.map((category) => <g key={category.key}><polygon points={area(category.key)} fill={category.color} opacity={filter === 'all' ? 0.05 : 0.16} /><polyline points={points(category.key)} fill="none" stroke={category.color} strokeWidth={filter === category.key ? 3.5 : 2.5} strokeLinejoin="round" strokeLinecap="round" /></g>)}{history.map((row, index) => <g key={`${row.quarter}-${index}`}><text x={xAt(index)} y="176" textAnchor="middle" className="fill-slate-400 text-[8px]">{periodLabel(row.quarter)}</text><rect x={xAt(index) - Math.max(12, (chart.right - chart.left) / Math.max(2, history.length) / 2)} y={chart.top} width={Math.max(24, (chart.right - chart.left) / Math.max(1, history.length))} height={chart.bottom - chart.top} fill="transparent" onMouseEnter={() => setHoveredIndex(index)} /><line x1={xAt(index)} x2={xAt(index)} y1={chart.top} y2={chart.bottom} stroke="#94a3b8" strokeDasharray="3 3" opacity={hoveredIndex === index ? 0.7 : 0} />{visibleCategories.map((category) => <circle key={category.key} cx={xAt(index)} cy={yAt(row[category.key])} r={hoveredIndex === index ? 4 : 2.5} fill={category.color} stroke="white" strokeWidth="1.5" />)}</g>)}</svg>{hovered && hoveredIndex != null && <Tooltip row={hovered} left={Math.max(4, Math.min(74, xAt(hoveredIndex) / 6 - 15))} />}</div></div>
    </div> : <OwnershipTable history={history} latest={latest} previous={previous} />}

    <div className="grid grid-cols-2 gap-2 sm:grid-cols-5"><Metric label="Institutional holding" value={formatSafePct(institutional, false)} /><Metric label="Public holding" value={formatSafePct(latest.public, false)} /><Metric label="Periods available" value={String(selectedRows.length)} /><Metric label="Promoter pledged" value={formatSafePct(latest.pledged, false)} /><Metric label="Shareholders" value={latestShareholders == null ? '—' : new Intl.NumberFormat('en-IN', { notation: 'compact', maximumFractionDigits: 2 }).format(latestShareholders)} /></div>
    {topInstitutions.length > 0 && <div className="rounded-xl border border-slate-200 dark:border-slate-800"><div className="flex items-center justify-between gap-3 border-b border-slate-200 px-4 py-3 dark:border-slate-800"><div><h3 className="text-xs font-black">Top reported holders</h3><p className="mt-0.5 text-[9px] text-slate-400">Largest named holdings disclosed for {periodLabel(latest.quarter, true)}</p></div>{topInstitutions.length > 8 && <button type="button" onClick={() => setShowAllHolders((value) => !value)} className="shrink-0 text-[10px] font-bold text-sky-600 hover:text-sky-700">{showAllHolders ? 'Show less' : `View all ${topInstitutions.length}`}</button>}</div><div className="grid divide-y divide-slate-100 md:grid-cols-2 md:divide-x md:divide-y-0 dark:divide-slate-800">{(showAllHolders ? topInstitutions : topInstitutions.slice(0, 8)).map((holder, index) => <div key={`${holder.name}-${index}`} className="flex items-center justify-between gap-4 px-4 py-3"><div className="min-w-0"><p className="truncate text-[11px] font-bold text-slate-900 dark:text-white" title={holder.name}>{holder.name}</p><span className="text-[9px] font-semibold uppercase tracking-wide text-slate-400">{holder.category}</span></div><strong className="shrink-0 text-xs tabular-nums text-sky-600">{formatSafePct(holder.holding_pct, false)}</strong></div>)}</div></div>}
    {frequency === 'annual' && <p className="text-[9px] text-slate-400">Annual view uses the latest valid reported quarter available in each calendar year.</p>}
  </div>;
}

function Toggle({ values, selected, onSelect, dark = false }: { values: string[]; selected: string; onSelect: (value: string) => void; dark?: boolean }) { return <div className="flex rounded-lg border border-slate-200 bg-white p-0.5 dark:border-slate-700 dark:bg-slate-900">{values.map((item) => <button type="button" key={item} onClick={() => onSelect(item)} className={`rounded-md px-2.5 py-1 text-[8px] font-bold uppercase tracking-wide ${selected === item ? dark ? 'bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900' : 'bg-sky-600 text-white' : 'text-slate-500 hover:text-sky-600'}`}>{item}</button>)}</div>; }
function Tooltip({ row, left }: { row: HoldingRow; left: number }) { return <div className="pointer-events-none absolute top-2 z-10 min-w-40 rounded-xl border border-slate-200 bg-white/95 p-3 text-[10px] shadow-xl dark:border-slate-700 dark:bg-slate-950/95" style={{ left: `${left}%` }}><strong className="mb-2 block">{periodLabel(row.quarter, true)}</strong>{categories.map((category) => <span key={category.key} className="mb-1 grid grid-cols-[10px_1fr_auto] items-center gap-2"><i className={`h-2 w-2 rounded-full ${category.className}`} /><span>{category.shortLabel}</span><b>{formatSafePct(row[category.key], false)}</b></span>)}</div>; }
function OwnershipTable({ history, latest, previous }: { history: HoldingRow[]; latest: HoldingRow; previous?: HoldingRow }) { return <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="w-full min-w-[900px] text-[10px]"><thead className="bg-slate-50 text-slate-500 dark:bg-slate-950"><tr><th className="sticky left-0 z-10 bg-inherit px-4 py-3 text-left">Category</th>{history.map((row) => <th key={row.quarter} className="px-3 py-3 text-center">{periodLabel(row.quarter)}</th>)}<th className="px-3 py-3 text-center">Change</th><th className="px-3 py-3 text-center">Trend</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{categories.map((category) => { const change = changeBetween(latest[category.key], previous?.[category.key]); return <tr key={category.key}><th className="sticky left-0 bg-white px-4 py-3 text-left dark:bg-slate-900"><span className="flex items-center gap-2"><i className={`h-2.5 w-2.5 rounded-full ${category.className}`} />{category.label}</span></th>{history.map((row) => <td key={row.quarter} className="px-3 py-3 text-center tabular-nums">{formatSafePct(row[category.key], false)}</td>)}<td className="px-3 py-3 text-center"><Trend value={change} /></td><td className="px-3 py-3 text-center"><span className={`rounded-full px-2 py-1 font-bold ${change == null || Math.abs(change) < 0.5 ? 'bg-slate-100 text-slate-600 dark:bg-slate-800' : change > 0 ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950' : 'bg-rose-100 text-rose-700 dark:bg-rose-950'}`}>{change == null || Math.abs(change) < 0.5 ? 'Stable' : change > 0 ? 'Increasing' : 'Decreasing'}</span></td></tr>; })}</tbody></table></div>; }
