'use client';

import { useCallback, useEffect, useRef, useState, type ReactNode } from 'react';
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, Building2, CheckCircle2, ChevronRight, FileText, Globe, LineChart, PieChart, ShieldCheck, Sparkles, Target, TrendingUp, Users, WalletCards, XCircle } from 'lucide-react';
import type { StockCandle, StockMasterDetail } from '../types';
import { getStockChart } from '../api';
import { formatMarketCap, formatSafeNumber, formatSafePct, formatSafePrice, formatSafeVolume, getCurrencySymbol } from '../utils/mappers';
import CompanyLogo from './CompanyLogo';
import ShareholdingCharts from './ShareholdingCharts';
import StockCandleChart from './StockCandleChart';
import DeliveryParticipation from './DeliveryParticipation';

interface Props { detail: StockMasterDetail; onSelectPeer?: (symbol: string) => void; isStandalonePage?: boolean }
const chartRanges = [{ label: '1D', range: '1D', interval: '5m' }, { label: '1W', range: '1W', interval: '1h' }, { label: '1M', range: '1M', interval: '1d' }, { label: '3M', range: '3M', interval: '1d' }, { label: '6M', range: '6M', interval: '1d' }, { label: '1Y', range: '1Y', interval: '1wk' }, { label: '5Y', range: '5Y', interval: '1mo' }] as const;
type ChartRange = typeof chartRanges[number]['label'];
const panel = 'rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900';

function Title({ children, icon, aside }: { children: ReactNode; icon?: ReactNode; aside?: ReactNode }) {
  return <div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm font-black text-slate-900 dark:text-white">{icon && <span className="text-sky-600">{icon}</span>}{children}</div>{aside}</div>;
}
function Stat({ label, value, note }: { label: string; value: ReactNode; note?: string }) {
  return <div className="rounded-xl border border-slate-200 bg-slate-50/70 p-3 dark:border-slate-800 dark:bg-slate-950/40"><span className="block text-[9px] font-bold uppercase tracking-wide text-slate-400">{label}</span><strong className="mt-1 block text-sm tabular-nums text-slate-900 dark:text-white">{value}</strong>{note && <span className="mt-0.5 block text-[9px] text-slate-500">{note}</span>}</div>;
}
function RangeLine({ low, high, current, currency }: { low?: number; high?: number; current?: number; currency: string }) {
  const position = low != null && high != null && current != null && high > low ? Math.max(0, Math.min(100, (current - low) / (high - low) * 100)) : 50;
  return <div><div className="mb-1 flex justify-between text-[10px] font-bold"><span>{formatSafePrice(low, currency)}</span><span>{formatSafePrice(high, currency)}</span></div><div className="relative h-1.5 rounded-full bg-slate-200 dark:bg-slate-700"><i className="absolute top-1/2 h-3 w-1.5 -translate-x-1/2 -translate-y-1/2 rounded bg-emerald-500" style={{ left: `${position}%` }} /></div></div>;
}

export default function StockDetailDashboard({ detail, onSelectPeer }: Props) {
  const { company, quote, metrics, header, today_at_a_glance: glance, shariah_audit: audit, valuation_and_sector_context: valuation, growth_and_profitability: growth, financial_health_and_cash_flow: health, technical_analysis: technical, quarterly_financials, annual_financials, shareholding_pattern, delivery_conviction, peers, investor_faqs, flags, thesis, trader_insights, chart } = detail;
  const currency = getCurrencySymbol(company.country || company.currency);
  const positive = Number(quote.change_percentage || 0) >= 0;
  const compliant = audit?.overall_result === 'PASS' || header?.is_shariah_compliant || detail.shariah_compliance.status === 'HALAL';
  const [range, setRange] = useState<ChartRange>('1Y');
  const [candles, setCandles] = useState<StockCandle[]>(chart || []);
  const [chartLoading, setChartLoading] = useState(false);
  const [period, setPeriod] = useState<'annual' | 'quarterly'>('annual');
  const first = useRef(true);
  const fetchChart = useCallback(async (selected: ChartRange) => { const config = chartRanges.find((item) => item.label === selected); if (!config) return; setChartLoading(true); const result = await getStockChart(company.symbol, config.range, config.interval, company.country); setCandles(result?.candles || chart || []); setChartLoading(false); }, [chart, company.country, company.symbol]);
  useEffect(() => { if (first.current) { first.current = false; return; } void fetchChart(range); }, [fetchChart, range]);

  const recent = detail.what_changed_recently || [];
  const actions = detail.corporate_actions || [];
  const financials = period === 'annual' ? annual_financials || [] : quarterly_financials || [];
  const holdingRows = (shareholding_pattern || []).filter((row) => row.promoter != null || row.fii != null || row.dii != null || row.public != null);
  const holding = holdingRows[0];
  const rawGrowthSeries = growth?.chart_series || [];
  const growthSeries = Array.from(rawGrowthSeries.reduce((rows, row) => {
    const existing = rows.get(row.period);
    if (!existing || Number(row.revenue || 0) > Number(existing.revenue || 0)) rows.set(row.period, row);
    return rows;
  }, new Map<string, (typeof rawGrowthSeries)[number]>()).values()).sort((a, b) => a.period.localeCompare(b.period));
  const maxRevenue = Math.max(1, ...growthSeries.map((row) => Number(row.revenue || 0)));
  const maxProfit = Math.max(1, ...growthSeries.map((row) => Math.abs(Number(row.net_income || 0))));
  const valuationRows = [['P/E', valuation?.company?.pe_ratio, valuation?.sector_medians?.pe_ratio], ['Forward P/E', valuation?.company?.forward_pe, valuation?.sector_medians?.forward_pe], ['P/B', valuation?.company?.price_to_book, valuation?.sector_medians?.price_to_book], ['EV/EBITDA', valuation?.company?.ev_to_ebitda, valuation?.sector_medians?.ev_to_ebitda], ['PEG', valuation?.company?.peg_ratio, valuation?.sector_medians?.peg_ratio], ['Earnings yield', valuation?.company?.earnings_yield, valuation?.sector_medians?.earnings_yield]] as const;
  const nav = [['overview', 'Overview', true], ['chart', 'Chart', true], ['financials', 'Financials', financials.length > 0], ['valuation', 'Ratios', Boolean(valuation)], ['technical', 'Technical', Boolean(technical)], ['ownership', 'Shareholding', Boolean(holding)], ['delivery', 'Delivery', Boolean(delivery_conviction?.length)], ['actions', 'Corporate Actions', actions.length > 0], ['peers', 'Peers', Boolean(peers?.length)], ['about', 'About', Boolean(company.description)]].filter((item) => item[2]);
  const topMetrics = [
    ['Market cap', formatMarketCap(metrics.market_cap, company.country)],
    ['P/E TTM', formatSafeNumber(metrics.pe_ratio, 2)],
    ['Forward P/E', formatSafeNumber(metrics.forward_pe, 2)],
    ['P/B', formatSafeNumber(metrics.price_to_book, 2)],
    ['EPS TTM', formatSafePrice(metrics.eps, currency)],
    ['ROCE', formatSafePct(metrics.roce, false)],
    ['ROE', formatSafePct(metrics.roe, false)],
    ['D/E', formatSafeNumber(metrics.debt_to_equity, 2)],
    ['Dividend yield', formatSafePct(metrics.dividend_yield, false)],
    ['PEG', formatSafeNumber(metrics.peg_ratio, 2)],
  ].filter(([, value]) => value !== '—');
  const passedCriteria = audit?.criteria_breakdown?.filter((row) => row.status === 'PASS').length || 0;
  const totalCriteria = audit?.criteria_breakdown?.length || 0;

  return <div className="space-y-3">
    <section className={`${panel} p-5`}><div className="grid gap-5 lg:grid-cols-[1.15fr_0.8fr_0.8fr] lg:items-center">
      <div className="flex items-center gap-4"><CompanyLogo src={company.logo_url} symbol={company.symbol} name={company.name} size="xl" className="h-16 w-16 !rounded-xl" /><div className="min-w-0"><h1 className="truncate text-2xl font-black text-slate-950 dark:text-white">{company.name}</h1><p className="mt-1 text-xs font-bold text-slate-500">{company.exchange}: {company.symbol}</p><div className="mt-2 flex flex-wrap gap-1.5">{[company.industry, company.sector, trader_insights?.market_tier?.replace('_', ' ')].filter(Boolean).map((tag) => <span key={tag} className="rounded-md bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{tag}</span>)}</div></div></div>
      <div className="border-slate-200 lg:border-l lg:pl-6 dark:border-slate-800"><div className="text-3xl font-black tabular-nums">{formatSafePrice(quote.price, currency)}</div><div className={`mt-1 flex items-center gap-1 text-sm font-black ${positive ? 'text-emerald-600' : 'text-rose-600'}`}>{positive ? <ArrowUpRight className="h-4 w-4" /> : <ArrowDownRight className="h-4 w-4" />}{formatSafePrice(quote.change, currency)} ({formatSafePct(quote.change_percentage)})</div><p className="mt-1 text-[10px] text-slate-400">{header?.market_status_label || `${company.exchange} market data`}</p></div>
      <div className="flex flex-col gap-2 lg:items-end"><span className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-xs font-black ${compliant ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-rose-100 text-rose-700'}`}>{compliant ? <ShieldCheck className="h-4 w-4" /> : <XCircle className="h-4 w-4" />}{audit?.badge_label || header?.shariah_badge || detail.shariah_compliance.status}</span><span className="text-[10px] text-slate-400">Market cap {formatMarketCap(metrics.market_cap, company.country)}</span></div>
    </div></section>

    {topMetrics.length > 0 && <section className={`${panel} overflow-x-auto`} aria-label="Key stock metrics"><div className="flex min-w-max divide-x divide-slate-200 dark:divide-slate-800">{topMetrics.map(([label, value]) => <div key={label} className="min-w-32 flex-1 px-4 py-3"><span className="block text-[8px] font-bold uppercase tracking-wider text-slate-400">{label}</span><strong className="mt-1 block text-xs tabular-nums text-slate-900 dark:text-white">{value}</strong></div>)}</div></section>}

    <nav className="sticky top-14 z-20 flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white/95 px-2 shadow-sm backdrop-blur dark:border-slate-800 dark:bg-slate-950/95">{nav.map(([id, label]) => <button key={String(id)} onClick={() => document.getElementById(String(id))?.scrollIntoView({ behavior: 'smooth' })} className="shrink-0 border-b-2 border-transparent px-3 py-3 text-[11px] font-bold text-slate-500 hover:border-sky-500 hover:text-sky-600">{label}</button>)}</nav>

    <div id="overview" className="grid scroll-mt-28 gap-3 lg:grid-cols-[1.9fr_0.9fr]">
      <section id="chart" className={`${panel} scroll-mt-28 p-4`}><Title icon={<LineChart className="h-4 w-4" />} aside={<div className="flex rounded-lg bg-slate-100 p-1 dark:bg-slate-800">{chartRanges.map((item) => <button key={item.label} onClick={() => setRange(item.label)} className={`rounded-md px-2 py-1 text-[9px] font-bold ${range === item.label ? 'bg-sky-600 text-white' : 'text-slate-500'}`}>{item.label}</button>)}</div>}>Price chart</Title><StockCandleChart candles={candles} currencySymbol={currency} loading={chartLoading} range={range} /></section>
      {glance && <section className={`${panel} p-4`}><Title icon={<Activity className="h-4 w-4" />}>Today at a glance</Title><div className="space-y-5"><div><p className="mb-1 text-[10px] font-bold text-slate-500">Day range</p><RangeLine low={glance.day_range?.low} high={glance.day_range?.high} current={glance.day_range?.current} currency={currency} /></div><div><p className="mb-1 text-[10px] font-bold text-slate-500">52 week range</p><RangeLine low={glance.fifty_two_week_range?.low} high={glance.fifty_two_week_range?.high} current={quote.price} currency={currency} /></div><div className="grid grid-cols-2 gap-2"><Stat label="Volume" value={formatSafeVolume(glance.volume)} note={`${formatSafeNumber(glance.volume_ratio, 2)}x 20D avg`} /><Stat label="Free float" value={formatSafePct(glance.free_float_pct, false)} note={`${formatSafePct(glance.volume_diff_pct)} volume`} /></div>{glance.narrative_summary && <p className="rounded-xl bg-sky-50 p-3 text-[10px] leading-4 text-sky-800 dark:bg-sky-950/40 dark:text-sky-200">{glance.narrative_summary}</p>}</div></section>}
    </div>

    {technical && <section id="technical" className={`${panel} scroll-mt-28 p-4`}><Title icon={<Activity className="h-4 w-4" />}>Technical analysis</Title><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7"><Stat label="RSI (14)" value={formatSafeNumber(technical.rsi_14?.value, 1)} note={technical.rsi_14?.label} /><Stat label="MACD" value={<Signal value={technical.macd?.status} />} note={technical.macd?.label} /><Stat label="ATR (14)" value={formatSafePrice(technical.atr_14?.value, currency)} note={technical.atr_14?.label} />{['sma_20','sma_50','sma_100','sma_200'].map((key) => <Stat key={key} label={key.replace('_', ' ').toUpperCase()} value={formatSafePrice(technical.moving_averages?.[key]?.value, currency)} note={technical.moving_averages?.[key]?.status} />)}</div>{technical.cpr && <div className="mt-3 grid grid-cols-3 gap-2"><Stat label="CPR bottom" value={formatSafePrice(technical.cpr.bottom_central, currency)} /><Stat label="Pivot" value={formatSafePrice(technical.cpr.pivot, currency)} /><Stat label="CPR top" value={formatSafePrice(technical.cpr.top_central, currency)} /></div>}</section>}

    {recent.length > 0 && <section className={`${panel} p-4`}><Title icon={<Sparkles className="h-4 w-4" />}>What changed recently?</Title><div className="grid gap-3 md:grid-cols-3">{recent.slice(0, 3).map((item, index) => <div key={`${item.title}-${index}`} className="flex gap-3 border-slate-200 md:border-r md:pr-4 last:border-0 dark:border-slate-800"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-sky-50 text-sky-600 dark:bg-sky-950"><FileText className="h-4 w-4" /></span><div><p className="text-[9px] text-slate-400">{item.date}</p><p className="text-xs font-black">{item.title}</p><p className="mt-1 text-[10px] text-slate-500">{item.details}</p></div></div>)}</div></section>}

    {audit && <section className={`${panel} p-4`}><Title aside={<span className="text-[9px] text-slate-400">Methodology: {audit.methodology}</span>}>Shariah audit</Title><div className="grid gap-5 lg:grid-cols-[200px_1fr]"><div className="flex flex-col items-center justify-center py-2"><div className={`flex h-32 w-32 flex-col items-center justify-center rounded-full border-[10px] bg-white dark:bg-slate-900 ${audit.overall_result === 'PASS' ? 'border-emerald-500' : 'border-rose-500'}`}><strong className="text-xl">{audit.overall_result}</strong><span className="mt-0.5 text-[11px] text-slate-500">{totalCriteria ? `${passedCriteria}/${totalCriteria} criteria` : audit.criteria_summary}</span></div><span className={`mt-4 rounded-lg px-4 py-1.5 text-[11px] font-bold ${audit.overall_result === 'PASS' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : 'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300'}`}>{audit.badge_label}</span></div><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800"><table className="min-w-[700px] w-full text-xs"><thead className="bg-slate-50 text-left text-[9px] uppercase text-slate-400 dark:bg-slate-950"><tr><th className="p-3">Criteria</th><th className="p-3 text-right">Numerator</th><th className="p-3 text-right">Denominator</th><th className="p-3 text-right">Value</th><th className="p-3 text-right">Threshold</th><th className="p-3 text-right">Status</th></tr></thead><tbody>{(audit.criteria_breakdown || []).map((row) => <tr key={row.criteria} className="border-t border-slate-100 dark:border-slate-800"><td className="p-3 font-bold">{row.name}</td><td className="p-3 text-right">{formatMarketCap(row.numerator, company.country)}</td><td className="p-3 text-right">{formatMarketCap(row.denominator, company.country)}</td><td className="p-3 text-right font-black">{formatSafePct(row.value_pct, false)}</td><td className="p-3 text-right">{row.threshold_label}</td><td className={`p-3 text-right font-black ${row.status === 'PASS' ? 'text-emerald-600' : 'text-rose-600'}`}>{row.status}</td></tr>)}</tbody></table></div></div></section>}

    <div className="grid gap-3 lg:grid-cols-2">
      {valuation && <section id="valuation" className={`${panel} scroll-mt-28 p-4`}><Title>Valuation & sector context</Title><div className="grid grid-cols-[1fr_0.7fr_0.7fr_1fr] border-b border-slate-200 pb-2 text-[9px] font-bold uppercase text-slate-400"><span>Metric</span><span className="text-right">Company</span><span className="text-right">Sector</span><span /></div>{valuationRows.map(([label, own, median]) => <div key={label} className="grid grid-cols-[1fr_0.7fr_0.7fr_1fr] items-center border-b border-slate-100 py-2.5 text-xs last:border-0 dark:border-slate-800"><span className="font-bold">{label}</span><span className="text-right font-black">{formatSafeNumber(own, 2)}</span><span className="text-right text-slate-500">{formatSafeNumber(median, 2)}</span><span className="ml-3 h-1.5 rounded-full bg-slate-100 dark:bg-slate-800"><i className="block h-full rounded-full bg-sky-500" style={{ width: `${own != null && median ? Math.min(100, Number(own) / Number(median) * 65) : 0}%` }} /></span></div>)}</section>}
      {growth && <section className={`${panel} p-4`}><Title icon={<TrendingUp className="h-4 w-4" />} aside={<div className="flex gap-3 text-[9px] text-slate-500"><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-sky-500" />Revenue</span><span><i className="mr-1 inline-block h-2 w-2 rounded-sm bg-emerald-500" />PAT</span></div>}>Growth & profitability</Title><div className="flex h-44 items-end gap-5 border-b border-slate-100 px-3 pb-2 dark:border-slate-800">{growthSeries.map((row) => <div key={row.period} className="flex h-full flex-1 flex-col justify-end text-center"><div className="flex flex-1 items-end justify-center gap-2"><div className="w-8 rounded-t bg-sky-500" style={{ height: `${Math.max(10, Number(row.revenue || 0) / maxRevenue * 100)}%` }} title={`Revenue: ${formatMarketCap(row.revenue, company.country)}`} /><div className={`w-8 rounded-t ${Number(row.net_income || 0) >= 0 ? 'bg-emerald-500' : 'bg-rose-500'}`} style={{ height: `${Math.max(10, Math.abs(Number(row.net_income || 0)) / maxProfit * 72)}%` }} title={`PAT: ${formatMarketCap(row.net_income, company.country)}`} /></div><span className="mt-1 text-[9px] font-bold">{row.period}</span><span className="text-[8px] text-slate-400">PAT margin <b className="text-emerald-600">{formatSafePct(row.pat_margin_pct, false)}</b></span></div>)}</div><p className="mt-1 text-[8px] text-slate-400">Revenue and PAT bars use independent scales to make their year-on-year direction readable.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="Revenue CAGR 3Y" value={formatSafePct(growth.cagr?.revenue_cagr_3y)} /><Stat label="Revenue CAGR 5Y" value={formatSafePct(growth.cagr?.revenue_cagr_5y)} /><Stat label="PAT CAGR 3Y" value={formatSafePct(growth.cagr?.pat_cagr_3y)} /><Stat label="PAT CAGR 5Y" value={formatSafePct(growth.cagr?.pat_cagr_5y)} /></div></section>}
    </div>

    <div className="grid gap-3 lg:grid-cols-2">
      {health && <section className={`${panel} p-4`}><Title icon={<WalletCards className="h-4 w-4" />}>Financial health & cash flow</Title><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="Net debt" value={formatMarketCap(health.net_debt, company.country)} note={health.health_status} /><Stat label="Interest coverage" value={`${formatSafeNumber(health.interest_coverage, 2)}x`} note="EBIT / interest" /><Stat label="CFO / PAT" value={`${formatSafeNumber(health.cfo_to_pat_3y, 2)}x`} note="3Y average" /><Stat label="Net debt / EBITDA" value={health.net_debt_to_ebitda == null ? '—' : `${formatSafeNumber(health.net_debt_to_ebitda, 2)}x`} note="Leverage" /></div><div className="mt-3 grid grid-cols-2 gap-2"><Stat label="Operating cash flow" value={formatMarketCap(health.cash_flow?.operating_cash_flow, company.country)} /><Stat label="Free cash flow" value={formatMarketCap(health.cash_flow?.free_cash_flow, company.country)} /></div></section>}
      {financials.length > 0 && <section id="financials" className={`${panel} scroll-mt-28 p-4`}><Title icon={<FileText className="h-4 w-4" />} aside={<div className="rounded-lg bg-slate-100 p-1 dark:bg-slate-800"><button onClick={() => setPeriod('annual')} className={`rounded-md px-3 py-1 text-[9px] font-bold ${period === 'annual' ? 'bg-sky-600 text-white' : ''}`}>Annual</button><button onClick={() => setPeriod('quarterly')} className={`rounded-md px-3 py-1 text-[9px] font-bold ${period === 'quarterly' ? 'bg-sky-600 text-white' : ''}`}>Quarterly</button></div>}>Financial statements</Title><div className="overflow-x-auto"><table className="min-w-[520px] w-full text-[10px]"><thead className="bg-slate-50 text-slate-400 dark:bg-slate-950"><tr><th className="p-2 text-left">Period</th><th className="p-2 text-right">Revenue</th><th className="p-2 text-right">Operating profit</th><th className="p-2 text-right">PAT</th><th className="p-2 text-right">EPS</th></tr></thead><tbody>{financials.slice(0, 6).map((row, index) => <tr key={index} className="border-t border-slate-100 dark:border-slate-800"><td className="p-2 font-bold">{'fiscal_quarter' in row ? `Q${row.fiscal_quarter} ` : ''}FY{row.fiscal_year}</td><td className="p-2 text-right">{formatMarketCap(row.revenue, company.country)}</td><td className="p-2 text-right">{formatMarketCap(row.operating_income, company.country)}</td><td className="p-2 text-right font-bold text-emerald-600">{formatMarketCap(row.net_income, company.country)}</td><td className="p-2 text-right">{formatSafePrice(row.diluted_eps, currency)}</td></tr>)}</tbody></table></div></section>}
    </div>

    {(flags.green_flags.length > 0 || flags.red_flags.length > 0) && <section className={`${panel} p-4`}><Title icon={<Target className="h-4 w-4" />}>Strengths, risks & investment thesis</Title><div className="grid gap-3 lg:grid-cols-[1fr_1fr_0.9fr]"><div className="rounded-xl border border-emerald-200 bg-emerald-50/70 p-4 dark:border-emerald-900 dark:bg-emerald-950/20"><h3 className="mb-2 text-xs font-black text-emerald-700">Strengths</h3>{flags.green_flags.map((item) => <p key={item} className="mb-1.5 flex gap-2 text-[10px]"><CheckCircle2 className="h-3 w-3 shrink-0 text-emerald-600" />{item}</p>)}</div><div className="rounded-xl border border-rose-200 bg-rose-50/70 p-4 dark:border-rose-900 dark:bg-rose-950/20"><h3 className="mb-2 text-xs font-black text-rose-700">Risks</h3>{flags.red_flags.map((item) => <p key={item} className="mb-1.5 flex gap-2 text-[10px]"><AlertTriangle className="h-3 w-3 shrink-0 text-rose-600" />{item}</p>)}</div><div className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><p className="text-[10px] font-black text-emerald-600">Bull case</p><p className="mb-3 mt-1 text-[10px]">{thesis.bull_case[0] || '—'}</p><p className="text-[10px] font-black text-rose-600">Bear case</p><p className="mb-3 mt-1 text-[10px]">{thesis.bear_case[0] || '—'}</p><p className="text-[10px] font-black text-sky-600">Flip condition</p><p className="mt-1 text-[10px]">{thesis.flip_conditions[0] || '—'}</p></div></div></section>}

    <div className={`grid gap-3 ${holding && actions.length > 0 ? 'lg:grid-cols-[1.35fr_1fr]' : 'grid-cols-1'}`}>
      {holding && <section id="ownership" className={`${panel} scroll-mt-28 p-4 sm:p-5`}>
        <Title icon={<PieChart className="h-4 w-4" />}>Shareholding pattern</Title>
        <ShareholdingCharts rows={holdingRows} />
      </section>}
      {actions.length > 0 && <section id="actions" className={`${panel} scroll-mt-28 p-4`}><Title>Corporate actions & dividends</Title><div className="divide-y divide-slate-100 dark:divide-slate-800">{actions.slice(0, 6).map((item, index) => <div key={index} className="grid grid-cols-[0.7fr_0.8fr_1.6fr] gap-2 py-2 text-[10px]"><span>{item.date}</span><strong>{item.type}</strong><span>{item.details}</span></div>)}</div></section>}
    </div>

    {delivery_conviction?.length ? <DeliveryParticipation rows={delivery_conviction} /> : null}

    {peers?.length ? <section id="peers" className={`${panel} scroll-mt-28 p-4`}><Title icon={<Users className="h-4 w-4" />}>Sector peer comparison</Title><div className="overflow-x-auto"><table className="min-w-[580px] w-full text-[10px]"><thead className="text-left text-slate-400"><tr><th className="pb-2">Company</th><th className="pb-2 text-right">Market cap</th><th className="pb-2 text-right">P/E</th><th className="pb-2 text-right">ROE</th><th /></tr></thead><tbody>{peers.slice(0, 6).map((peer) => <tr key={peer.symbol} className="border-t border-slate-100 dark:border-slate-800"><td className="py-2 font-bold">{peer.company_name}</td><td className="py-2 text-right">{formatMarketCap(peer.market_cap, company.country)}</td><td className="py-2 text-right">{formatSafeNumber(peer.pe_ratio, 1)}</td><td className="py-2 text-right">{formatSafePct(peer.roe, false)}</td><td className="py-2 text-right"><button onClick={() => onSelectPeer?.(peer.symbol)} className="font-bold text-sky-600">Analyze <ChevronRight className="inline h-3 w-3" /></button></td></tr>)}</tbody></table></div></section> : null}

    <div className="grid gap-3 lg:grid-cols-2">
      {company.description && <section id="about" className={`${panel} scroll-mt-28 p-4`}><Title icon={<Building2 className="h-4 w-4" />}>About {company.name}</Title><div className="flex gap-4"><CompanyLogo src={company.logo_url} symbol={company.symbol} name={company.name} size="lg" /><div><p className="text-xs leading-5 text-slate-600 dark:text-slate-300">{company.description}</p><p className="mt-3 flex gap-3 text-[10px] text-slate-500"><span><Globe className="mr-1 inline h-3 w-3" />{company.country}</span><span>{company.sector}</span></p></div></div></section>}
      {investor_faqs?.length ? <section className={`${panel} p-4`}><Title>Questions investors ask</Title><div className="divide-y divide-slate-100 dark:divide-slate-800">{investor_faqs.map((faq) => <details key={faq.question} className="py-2"><summary className="cursor-pointer text-[11px] font-bold">{faq.question}</summary><p className="mt-2 text-[10px] leading-4 text-slate-500">{faq.answer}</p></details>)}</div></section> : null}
    </div>
    <p className="py-3 text-center text-[9px] text-slate-400">Market data is informational and may be delayed. Shariah screening follows the displayed methodology. This is not investment advice.</p>
  </div>;
}

function Signal({ value }: { value?: string }) {
  const normalized = value?.toLowerCase() || '';
  const tone = normalized.includes('bull') ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300' : normalized.includes('bear') ? 'bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300' : 'bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300';
  return <span className={`inline-flex rounded-md px-2 py-1 text-[10px] font-black uppercase tracking-wide ${tone}`}>{value || 'Neutral'}</span>;
}
