'use client';
import { ArrowUpDown, ArrowUpRight } from 'lucide-react';
import type { StockItem, StockSortField, SortDirection } from '../types';
import { formatCurrencyAmount, formatMarketCap } from '../utils/mappers';
import { ComplianceBadge } from './ComplianceBadge';
export interface StockTableProps { stocks: StockItem[]; sortField: StockSortField; sortDirection: SortDirection; onSort: (field: StockSortField) => void; onSelectStock: (stock: StockItem) => void; }
export default function StockTableView({stocks,sortField,sortDirection,onSort,onSelectStock}:StockTableProps) {
  const head=(label:string,field:StockSortField)=><th aria-sort={sortField===field?(sortDirection==='asc'?'ascending':'descending'):'none'}><button onClick={()=>onSort(field)} className="inline-flex items-center gap-2">{label}<ArrowUpDown size={12}/></button></th>;
  return <div className="surface overflow-x-auto"><table className="stock-table"><thead><tr>{head('Company','symbol')}{head('Price','price')}{head('Market cap','marketCapCr')}{head('P/E','pe_ratio')}<th>Debt / market cap</th><th>Screening</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{stocks.map(stock=><tr key={stock.id}><td><button onClick={()=>onSelectStock(stock)} className="company-cell"><span className="company-avatar">{stock.symbol.slice(0,2)}</span><span><strong>{stock.symbol}</strong><small>{stock.name}</small></span></button></td><td><strong>{formatCurrencyAmount(stock.price,stock.currencySymbol)}</strong><small className={stock.changePercent===null?'text-muted':stock.changePercent>=0?'text-positive':'text-negative'}>{stock.changePercent===null?'Change unavailable':(stock.changePercent>0?'+':'')+stock.changePercent.toFixed(2)+'%'}</small></td><td>{formatMarketCap(stock.marketCapCr===null?null:stock.marketCapCr*10000000,stock.country)}</td><td>{stock.fundamentals.peRatio?.toFixed(2)??'—'}</td><td>{stock.shariah.debtRatioPercent===null?'—':stock.shariah.debtRatioPercent.toFixed(2)+'%'}</td><td><ComplianceBadge status={stock.complianceStatus}/></td><td><button onClick={()=>onSelectStock(stock)} className="icon-button" aria-label={'View '+stock.symbol+' details'}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>;
}
